# -*- coding: utf-8 -*-
"""AggregationModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSfPzIy9H5W-cvSMJkeYeSc7s6znKgBT
"""

import pandas as pd

# -*- coding: utf-8 -*-
def aggregation(input):
  # dataframe containing all relevant data
  df = input

  total_comments = input.shape[0]
  positive_comments = 0
  negative_comments = 0
  neutral_comments = 0

  for i in range(0, total_comments - 1):
    if df["Label"][i] == "Positive":
      positive_comments += 1
    if df["Label"][i] == "Negative":
      negative_comments += 1
    if df["Label"][i] == "Neutral":
      neutral_comments += 1
  
  if (positive_comments >= negative_comments and positive_comments >= neutral_comments):
    return "positive"
  elif (negative_comments >= positive_comments and negative_comments >= neutral_comments): 
    return "negative"
  else:
    return "neutral"

def should_buy(input):
  outcome = aggregation(input)
  if outcome == "positive":
    return "r/WallStreetBets likes this stock."
  elif outcome == "negative":
    return "r/WallStreetBets does not like this stock."
  else:
    return "r/WallStreetBets is indifferent about this stock"

def main():
    # Read in CVS result file with pandas
    input = pd.read_csv('Labeled_data.csv') 

    # Call the aggregation function #
    decision = should_buy(input)

    print(decision)

if __name__ == '__main__':
    main()

""